name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Disk space before cleanup
      run: df -h
    - name: Cleanup
      run: sudo rm -rf /usr/local/lib/android /opt/ghc
    - name: Disk space after cleanup
      run: df -h
